branch-defaults:
  default:
    environment: RestApiTdd-env
environment-defaults:
  RestApiTdd-env:
    branch: null
    repository: null
global:
  application_name: rest_api_tdd
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:sa-east-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.8.1
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
